### ISSUE TITLE
StatsD reporter

### ISSUE THREAD

**Issue by antrix190** [gquintana/metrics-sql#4]
Is there any statsDReporter for the metrics collected by the framework?

**Comment by gquintana** [comment]
There are various StatsD reporters among Dropwizard extensions. Like https://github.com/ReadyTalk/metrics-statsd

**Comment by antrix190** [comment]
How do you configure it metrics-sql?

**Comment by gquintana** [comment]
It's not something metrics-sql specific, it's more metrics general.

With the mentioned extension metrics-statsd, it should be a matter of
```
StatsDReporter.forRegistry(registry)
    .build("statsd.example.com", 8125)
    .start(10, TimeUnit.SECONDS);
```
